# Generated by Django 4.2.2 on 2023-08-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folioTicket', models.CharField(default='', max_length=100, verbose_name='Folio Ticket')),
                ('descricpcionArchivo', models.CharField(default='', max_length=500, verbose_name='Descricpcion Archivo')),
                ('archivos', models.FileField(default='', upload_to='', verbose_name='Archivo')),
                ('fechaArchivo', models.DateTimeField(default=None, null=True, verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='', max_length=200, verbose_name='Calle')),
                ('colonia', models.CharField(default='', max_length=500, verbose_name='Colonia')),
                ('ciudad', models.CharField(default='', max_length=100, verbose_name='Colonia')),
                ('estado', models.CharField(default='', max_length=50, verbose_name='Colonia')),
                ('cp', models.CharField(default='', max_length=8, verbose_name='Colonia')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folioTicket', models.CharField(default='', max_length=50, verbose_name='Folio Ticket')),
                ('resumen', models.CharField(default='', max_length=500, verbose_name='Resumen')),
                ('archivosAdjuntos', models.CharField(default='', max_length=2, verbose_name='Archivos')),
                ('direccion', models.CharField(default='', max_length=300, verbose_name='Direccion')),
                ('fechaCreacion', models.DateTimeField(default=None, null=True, verbose_name='Fecha de creacion')),
                ('fechaActualizacion', models.DateTimeField(default=None, null=True, verbose_name='Fecha de modificacion')),
                ('usuarioEncargado', models.CharField(default='', max_length=50, verbose_name='Usuario encargado')),
                ('fechaAtencion', models.DateTimeField(default=None, null=True, verbose_name='Fecha de atencion')),
                ('fechaTerminacionPrevista', models.DateTimeField(default=None, null=True, verbose_name='Fecha de finalizacion programada')),
                ('fechaTerminacionFinal', models.DateTimeField(default=None, null=True, verbose_name='Fecha de finalizacion real')),
                ('statusTicket', models.CharField(default='', max_length=2, verbose_name='Status ticket')),
                ('nivelPrioridad', models.CharField(default='', max_length=2, verbose_name='Nivel de prioridad')),
                ('comentariosEncargado', models.CharField(default='', max_length=500, verbose_name='Comentarios')),
            ],
        ),
    ]
