# Generated by Django 4.2.4 on 2023-08-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folioTicket', models.CharField(default='', max_length=100, verbose_name='Folio Ticket')),
                ('descricpcionArchivo', models.CharField(default='', max_length=500, verbose_name='Descricpcion Archivo')),
                ('archivos', models.FileField(default='', upload_to='', verbose_name='Archivo')),
                ('fechaArchivo', models.DateField(default='', verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='', max_length=200, verbose_name='Calle')),
                ('colonia', models.CharField(default='', max_length=500, verbose_name='Colonia')),
                ('ciudad', models.CharField(default='', max_length=100, verbose_name='Colonia')),
                ('estado', models.CharField(default='', max_length=50, verbose_name='Colonia')),
                ('cp', models.CharField(default='', max_length=8, verbose_name='Colonia')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folioTicket', models.CharField(default='', max_length=100, verbose_name='Folio Ticket')),
                ('resumen', models.CharField(default='', max_length=500, verbose_name='Resumen')),
                ('archivosAdjuntos', models.BooleanField(default=0, verbose_name='Archivos')),
                ('fechaCreacion', models.DateField(default='', verbose_name='Fecha de creacion')),
                ('direccion', models.CharField(default='', max_length=300, verbose_name='Direccion')),
                ('fechaActualizacion', models.IntegerField(default=0, verbose_name='Fecha de modificacion')),
                ('usuarioEncargado', models.IntegerField(default=0, verbose_name='No. de Paginas')),
                ('fechaAtencion', models.IntegerField(default=0, verbose_name='Fecha de modificacion')),
                ('fechaTerminacionPrevista', models.IntegerField(default=0, verbose_name='Fecha de modificacion')),
                ('fechaTerminacionFinal', models.IntegerField(default=0, verbose_name='Fecha de modificacion')),
                ('statusTicket', models.CharField(default='', max_length=2, verbose_name='Direccion')),
                ('nivelPrioridad', models.CharField(default='', max_length=50, verbose_name='Nivel de prioridad')),
                ('comentariosEncargado', models.CharField(default='', max_length=500, verbose_name='Comentarios')),
            ],
        ),
    ]
