# Generated by Django 4.2.4 on 2023-08-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_direcciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivos',
            old_name='fechaArchivo',
            new_name='fechaCreacion',
        ),
    ]
