# Generated by Django 4.2.4 on 2023-08-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_tickets_fechaactualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='fechaActualizacion',
            field=models.DateField(default='', verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fechaAtencion',
            field=models.DateField(default='', verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fechaTerminacionFinal',
            field=models.DateField(default='', verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fechaTerminacionPrevista',
            field=models.DateField(default='', verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='usuarioEncargado',
            field=models.CharField(default='', max_length=50, verbose_name='No. de Paginas'),
        ),
    ]
