# Generated by Django 4.2.4 on 2023-08-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tickets_fechaatencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='nivelPrioridad',
            field=models.CharField(default='', max_length=2, verbose_name='Nivel de prioridad'),
        ),
    ]
