# Generated by Django 4.2.4 on 2023-08-19 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tickets_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
