# Generated by Django 4.2.4 on 2023-08-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tickets_nivelprioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='comentariosEncargado',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='fechaActualizacion',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='fechaAtencion',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='fechaTerminacionFinal',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='fechaTerminacionPrevista',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='nivelPrioridad',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='statusTicket',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='usuarioEncargado',
        ),
    ]
