# Generated by Django 4.2.4 on 2023-08-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_archivos_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='descripcion',
            field=models.CharField(default='', max_length=1000, verbose_name='Resumen'),
        ),
    ]
