# Generated by Django 4.2.4 on 2023-08-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_tickets_comentariosencargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='comentariosEncargado',
            field=models.CharField(default='', max_length=500, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fechaActualizacion',
            field=models.DateField(default='', verbose_name='Fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fechaAtencion',
            field=models.DateField(default='', verbose_name='Fecha de atencion'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fechaCreacion',
            field=models.DateField(default='', verbose_name='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fechaTerminacionFinal',
            field=models.DateField(default='', verbose_name='Fecha de finalizacion real'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fechaTerminacionPrevista',
            field=models.DateField(default='', verbose_name='Fecha de finalizacion programada'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='nivelPrioridad',
            field=models.CharField(default='', max_length=2, verbose_name='Nivel de prioridad'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='statusTicket',
            field=models.CharField(default='', max_length=2, verbose_name='Status ticket'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='usuarioEncargado',
            field=models.CharField(default='', max_length=50, verbose_name='Usuario encargado'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='archivosAdjuntos',
            field=models.CharField(default=0, max_length=2, verbose_name='Archivos'),
        ),
    ]
