# Generated by Django 4.2.2 on 2023-08-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_tickets_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivos',
            field=models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='Archivo'),
        ),
    ]
