# Generated by Django 4.2.4 on 2023-08-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_archivos_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='statusTicket',
            field=models.CharField(default='', max_length=15, verbose_name='Status ticket'),
        ),
    ]
