# Generated by Django 4.2.4 on 2023-08-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_tickets_statusticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='nivelPrioridad',
            field=models.CharField(default='', max_length=15, verbose_name='Nivel de prioridad'),
        ),
    ]
