# Generated by Django 4.2.2 on 2023-06-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20230613_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='pagina',
            new_name='paginas',
        ),
        migrations.AlterField(
            model_name='libros',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
